### ISSUE TITLE
Failed to obtain connection

### ISSUE THREAD

**Issue by a-legrand** [bbenzikry/metabase-neo4j-driver#12]
I have this error trying to configure the connection to my neo4j database

> [Simba][Neo4jJDBCDriver](100041) An error has occurred during data source connection: Failed to obtain connection towards READ server. Known routing table is: Ttl 1614258567866, currentTime 1614258267882, routers AddressSet=[], writers AddressSet=[], readers AddressSet=[], database 'neo4j'

Tested with all available protocols

note: I can use my database from the neo4j browser, with same access configuration

**Comment by bbenzikry** [comment]
Hi @a-legrand, thanks for opening the issue. 
Can you give me some more information about how your cluster is setup? this error usually stems from connecting to a read replica instead of a core server.
What is your Neo4j version?
What version of the driver are you using? 
Do you have TLS enabled on the instance? 
Is neo4j deployed on K8s? if so, what is your service / ingress configuration like?

**Comment by a-legrand** [comment]
Hi @bbenzikry 
its a basic installation from their docker image neo4j:4.2.1, a single instance, there is no replica

I am using your v0.0.7 driver

No tls enabled

**Comment by bbenzikry** [comment]
I checked it locally. 
First, as explained in the driver docs, you must have APOC installed for the driver to connect properly. 
However, that doesn't seem to be the issue that's causing your problem. I think this is a bug in the underlying BI driver ( there's a new version out, I hope it's fixed upstream ) 
It seems the JDBC driver does not fallback to bolt. 

Please try connecting ( after installing APOC ), with the following JDBC connection properties
```
?&LogLevel=6;StrictlyUseBoltScheme=true
```
![image](https://user-images.githubusercontent.com/1993348/109164906-9fc76c80-7783-11eb-9860-6771985856ef.png)

**Comment by a-legrand** [comment]
Works like a charm! thanks :)

didn't find the APOC mention in the documentation

**Comment by bbenzikry** [comment]
Great, I'll close the issue. 
The APOC part is in the BI driver documentation which I link to ( it's a PDF I can't really use due to licensing ) 
I'll add relevant documentation to accommodate. 

I'll appreciate a star if you'll find the driver useful :)

**Comment by noam7700** [comment]
@bbenzikry 
> ```
> ?&LogLevel=6;StrictlyUseBoltScheme=true
> ```
> 

Im missing where to JDBC connection options, in the [docs](https://github.com/bbenzikry/metabase-neo4j-driver#working-with-a-relational-model-on-graphs) it says it should be under the _Protocol_ input
![image](https://github.com/bbenzikry/metabase-neo4j-driver/assets/41344731/9abcf936-d20e-4b0f-8c06-41b8dd99b52a)

Im using neo4j 4.4, and also the 0.0.7 driver
